services:
  db:
    image: mysql:latest
    container_name: st_db
    restart: unless-stopped
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./mysql:/var/lib/mysql

  db_test:
    image: mysql:latest
    container_name: st_db_test
    restart: unless-stopped
    ports:
      - "${DB_PORT_TEST}:3306"
    environment:
      - MYSQL_USER=${DB_USERNAME_TEST}
      - MYSQL_PASSWORD=${DB_PASSWORD_TEST}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_TEST}
      - MYSQL_DATABASE=${DB_DATABASE_TEST}

  pma:
    image: phpmyadmin:latest
    container_name: st_pma
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: subs_tracker
#    ports:
#      - "${APP_PORT}:3003"
#    environment:
#      - APP_PORT=${APP_PORT}
#    restart: unless-stopped
#    depends_on:
#      - db